config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post 'destroy_all' => 'home#destroy_all'

  get 'auto_search' => 'searches#auto_search'
  get 'search' => 'user_searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
  has_many :user_searches
  validates_uniqueness_of :search
  validates_presence_of :search

  def self.related_searches(search)
    where('search LIKE ?', "#{search}%")
      .order('user_searches_count DESC')
  end

  def self.get_by_prhase(search_phrase)
    select(:id)
      .find_by(search: search_phrase)
      .id
  end
end

app/models/user_search.rb
class UserSearch < ApplicationRecord
  belongs_to :search, counter_cache: true
  validates_presence_of :search_id
  
  def self.search(search_phrase)

    search = Search.new(search: search_phrase)

    unless search.save
      search_id = Search.get_by_prhase(search_phrase)
      create(search_id: search_id)
    else
      create(search_id: search.id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def destroy_all
    UserSearch.destroy_all
    Search.destroy_all

    redirect_to action: :index
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def auto_search
    @searches = Search.related_searches(params[:search])
    render json: @searches
  end
end

app/controllers/user_searches_controller.rb
class UserSearchesController < ApplicationController

  def search
    UserSearch.search(params[:search])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user_searches_helper.rb
module UserSearchesHelper
end

app/views/home/index.html.erb
<div id="root">
  <section class="hero is-success is-fullheight">
    <div class="hero-body">
      <div class="container">
        <h1 class="title is-1">
        	Realtime Search Box
        </h1>
        <%= form_tag(destroy_all_path, method: :post) do %>
          <button class="button is-danger" type="submit">Clean Database</button>
        <% end %>

        <typeahead></typeahead>
      </div>
    </div>
  </section>
</div>

<script>require('frontend/js/app').init();</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeSearchbox</title>
    <%= stylesheet_link_tag "app.css" %>
    <%= javascript_include_tag "vendor.js" %>
    <%= javascript_include_tag "app.js" %>
    <%= stylesheet_link_tag  'application' %>
    <%= breakfast_autoreload_tag %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>